### ISSUE TITLE
Table structure from the Summary description

### ISSUE THREAD

**Issue by b-rajesh** [nknapp/bootprint-openapi#52]
Hi 
I use the following in the swagger description 

` |Field | Description|

    |-----------|------------|

    |defaultMessage|Human readable message explaining the reason why the field
    value is erroneous.|

    |field|The name of the JSON field that contains an erroneous value.|

    |rejectedValue|The value that was submitted but rejected.|`

** Which produces the following the swagger editor screen  **

![doc](https://cloud.githubusercontent.com/assets/13655071/12835035/a6687630-cc00-11e5-81ff-49defc5487a5.png)

However when I run bootprint openapi , final html page is not having table structure as above. Could you please advise ?

**After bootprint openapi transformation**

![after_run](https://cloud.githubusercontent.com/assets/13655071/12835091/29b7f61e-cc01-11e5-9880-81d001bc88ff.png)

**Comment by nknapp** [comment]
Hi and thanks for using bootprint-swagger. This could be fixed for you [with a custom lesscss-file](#providing-themes-with-custom-less-files). Since this is the output of the `marked` markdown-renderer there is no partial to be adapted.

Your problem looks worth fixing though. Maybe `marked` can be configured (in the `bootprint-base`-package) to render tables with a custom css class to include borders.

But I can't get to it until next Wednesday (probably). A pull-request would be welcome. Ideally it would include a test-case to verify the resulting output (have a look at the tests in this module)

**Comment by b-rajesh** [comment]
thank you for the reply, I am not sure I could start this change before Wednesday. However I will start to go through documentation and see what i can do. If you are able to fix it before me, please give me a shout. 

thank for your contribution 

cheers
Rajesh

**Comment by nknapp** [comment]
Please do not hesitate to create issues for missing or bad documentation or to ask for specific developer questions. This is almost as important to me as the code itself.

**Comment by nknapp** [comment]
I am now working on it.

**Comment by b-rajesh** [comment]
thanks mate, it works as expected. I am in process of testing all of our swagger docs using this tool. I will definitely reach you if have any queries or issues. 

cheers
Rajesh
