### ISSUE TITLE
API Explorer from openapi/swagger

### ISSUE THREAD

**Issue by b-rajesh** [nknapp/bootprint-openapi#56]
Since openapi/swagger metadata can be used to generate both API documentation and API explorer, do you have any plans to create API explorer for the API interaction for a user ?  
Swagger has a tool, named swagger-ui to do the same.

**Comment by nknapp** [comment]
No, my goal when creating bootpring-swagger/bootpring-openapi was actually to provide printable documentation. I had not found any suitable tool at the time.
If you want an API-explorer, you should use `swagger-ui`. I don't think the OpenAPI-Specification has changed massively since OpenAPI was created from Swagger. They should still be the same so `swagger-ui` should work fine with OpenAPI-Specs.
